[package]
name = "branchsense-dataset"
description = "Dataset generator for BranchSense."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
branchsense-semantic = { path = "../branchsense-semantic" }
branchsense-evaluation = { path = "../branchsense-evaluation" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
